apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Quota
metadata:
  name: medium
  annotations:
    quota.tenantoperator.stakater.com/is-default: "false"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
