apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Quota
metadata:
  name: small
  annotations:
    quota.tenantoperator.stakater.com/is-default: "false"
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
