kind: Secret
apiVersion: v1
metadata:
  name: nexus-docker-config
data:
  .dockerconfigjson: >-
    ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9uZXh1cy1kb2NrZXItc3Rha2F0ZXItbmV4dXMuYXBwcy5wcmVwcm9kLmpsdndqbHM4Lmt1YmVhcHAuY2xvdWQiOiB7CiAgICAgICAgImF1dGgiOiAiWkc5amEyVnlMWFZ6WlhJNlVFOHdPV3BvU1VSR01HOXBiZz09IgogICAgICB9LAogICAgICAiaHR0cHM6Ly9uZXh1cy1kb2NrZXItc3Rha2F0ZXItbmV4dXMuYXBwcy5wcmVwcm9kLmpsdndqbHM4Lmt1YmVhcHAuY2xvdWQiOiB7CiAgICAgICAgImF1dGgiOiAiWkc5amEyVnlMWFZ6WlhJNlVFOHdPV3BvU1VSR01HOXBiZz09IgogICAgICB9CiAgICB9CiAgfQo=
  config: >-
    ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9uZXh1cy1kb2NrZXItc3Rha2F0ZXItbmV4dXMuYXBwcy5wcmVwcm9kLmpsdndqbHM4Lmt1YmVhcHAuY2xvdWQiOiB7CiAgICAgICAgImF1dGgiOiAiWkc5amEyVnlMWFZ6WlhJNlVFOHdPV3BvU1VSR01HOXBiZz09IgogICAgICB9LAogICAgICAiaHR0cHM6Ly9uZXh1cy1kb2NrZXItc3Rha2F0ZXItbmV4dXMuYXBwcy5wcmVwcm9kLmpsdndqbHM4Lmt1YmVhcHAuY2xvdWQiOiB7CiAgICAgICAgImF1dGgiOiAiWkc5amEyVnlMWFZ6WlhJNlVFOHdPV3BvU1VSR01HOXBiZz09IgogICAgICB9CiAgICB9CiAgfQo=
type: kubernetes.io/dockerconfigjson
