apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-278-stakater-nordmart-review-f85b6076
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: revert-270-renovate/patch-spring-boot
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-revert-270-renovate/patch-spring-boot
          version: '*'
      interval: 1m0s
      releaseName: revert-270-renovate/patch-spring-boot
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-278-f85b6076
