apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-253-stakater-nordmart-review-a91fdf1b
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: fix-log-error-method
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-fix-log-error-method
          version: '*'
      interval: 1m0s
      releaseName: fix-log-error-method
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-253-a91fdf1b
