apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-275-stakater-nordmart-review-bf42be38
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: renovate/de.flapdoodle.embed-de.flapdoodle.embed.
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-renovate/de.flapdoodle.embed-de.flapdoodle.embed.
          version: '*'
      interval: 1m0s
      releaseName: renovate/de.flapdoodle.embed-de.flapdoodle.embed.
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-275-bf42be38
