apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-230-stakater-nordmart-review-fd82dfd2
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: test14
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: load-test-14
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-load-test-14
          version: '*'
      interval: 1m0s
      releaseName: load-test-14
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: SNAPSHOT-PR-230-fd82dfd2
