apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-260-stakater-nordmart-review-8dd30f87
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: rasheedamir-patch-1
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-rasheedamir-patch-1
          version: '*'
      interval: 1m0s
      releaseName: rasheedamir-patch-1
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-260-8dd30f87
