apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-269-stakater-nordmart-review-046b7851
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: renovate/org.glassfish.jaxb-jaxb-runtime-4.0.x
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-renovate/org.glassfish.jaxb-jaxb-runtime-4.0.x
          version: '*'
      interval: 1m0s
      releaseName: renovate/org.glassfish.jaxb-jaxb-runtime-4.0.x
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-269-046b7851
