apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-315-stakater-nordmart-review-dde32b2e
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: stress-test-pipeline/stp-1
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-stress-test-pipeline/stp-1
          version: '*'
      interval: 1m0s
      releaseName: stress-test-pipeline/stp-1
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-315-dde32b2e
