apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-380-stakater-nordmart-review-c48b3750
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: alpha
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: pipeline
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-pipeline
          version: '*'
      interval: 1m0s
      releaseName: pipeline
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-380-ac7d2668
