apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-373-stakater-nordmart-review-a9ba3302
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: mustafa-stress-test-pipeline-2
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-mustafa-stress-test-pipeline-2
          version: '*'
      interval: 1m0s
      releaseName: mustafa-stress-test-pipeline-2
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review
              tag: snapshot-pr-373-1f27032f
