apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Tenant
metadata:
  name: gabbar
spec:
  users:
    owner:
    - nebojsa
    - bilal.bokharee@stakater.com
    - hanzala@stakater.com
  quota: medium
  namespacetemplate:
    templateInstances:
    - spec:
        template: tenant-vault-access
        sync: true
      selector:
        matchExpressions:
        - {key: kind, operator: In, values: [dev,pr]}
