apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Tenant
metadata:
  name: veeru
spec:
  users:
    owner:
    - bilal.bokharee@stakater.com
    # Test user for Stakater Cloud IAM
    - sro-privileged
  quota: medium
  namespacetemplate:
    templateInstances:
    - spec:
        template: tenant-vault-access    
        sync: true
      selector:
        matchExpressions:
        - {key: kind, operator: In, values: [dev,pr]}
