apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: stakater-rollback-commit-v1
spec:
  params:
  steps:
  - image: registry.access.redhat.com/ubi8/nodejs-16
    name: e2e
    script: |
      
  workspaces:
  - name: source