apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: stakater-nordmart-inventory-59
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-inventory
        ref: test-pr
        path: deploy
        secretRef:
          null
      releaseName: test-pr
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-inventory
              tag: SNAPSHOT-PR-59-3024d697
  namespaceLabels:
    kind: pr
    team: gabbar
    stakater.com/tenant: veeru
