apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chelsea-preview-stakater-nordmart-review
  namespace: rh-openshift-gitops-instance
  labels:
    stakater.com/tenant: chelsea
    stakater.com/env: preview
    stakater.com/kind: preview      
spec:
  destination:
    namespace: chelsea-preview
    server: 'https://kubernetes.default.svc'
  project: chelsea
  source:
    path: 02-chelsea/01-stakater-nordmart-review-api/00-preview
    repoURL: 'https://github.com/AsfaMumtaz/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
