apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-preview-inventory
  namespace: openshift-stakater-argocd
  labels:
    tenant.stakater.com/name: "veeru"
    env.stakater.com/name: "preview"
    env.stakater.com/kind: "preview"     
spec:
  destination:
    namespace: veeru-preview
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/apps/01-stakater-nordmart-inventory/00-preview
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
  project: veeru-preview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true