apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: stakater-nordmart-inventory-79
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-inventory
        ref: test
        path: deploy
        secretRef:
          null
      releaseName: test
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-inventory
              tag: SNAPSHOT-PR-79-04e47446
  namespaceLabels:
    kind: pr
    team: gabbar
    stakater.com/tenant: veeru
