apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: stakater-nordmart-inventory-77
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-inventory
        ref: AsfaMumtaz-patch-9
        path: deploy
        secretRef:
          null
      releaseName: AsfaMumtaz-patch-9
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-inventory
              tag: SNAPSHOT-PR-77-03aff64d
  namespaceLabels:
    kind: pr
    team: gabbar
    stakater.com/tenant: veeru
