apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: pr-97-stakater-nordmart-inventory
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-inventory
        ref: bilalbokharee-patch-1
        path: deploy
        secretRef:
          null
      releaseName: bilalbokharee-patch-1
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-inventory
              tag: SNAPSHOT-PR-97-b9021abf
  namespaceLabels:
    kind: pr
    team: gabbar
    stakater.com/tenant: veeru
