apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: pr-96-stakater-nordmart-inventory
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-inventory
        ref: MuneebAijaz-patch-3
        path: deploy
        secretRef:
          null
      releaseName: MuneebAijaz-patch-3
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-inventory
              tag: SNAPSHOT-PR-96-5a6529c7
  namespaceLabels:
    kind: pr
    team: gabbar
    stakater.com/tenant: veeru
