
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: 03-sre/02-stage-prod/tenant-operator-config
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    directory:
       recurse: true
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

