apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: stakater-nordmart-review-37
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-review
        ref: pipeline
        path: deploy
        secretRef:
          null
      releaseName: pipeline
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review
              tag: SNAPSHOT-PR-37-2ac89f9b
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
