apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: stakater-nordmart-review-pr-2
spec:
  sourceBranch: update-tronador-yaml
  targetBranch: main
  triggeringRepoURL: https://github.com/stakater-lab/stakater-nordmart-review
