apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: stakater-nordmart-review-19
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-review
        ref: add-tronador
        path: deploy
        secretRef:
          null
      releaseName: add-tronador
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review
              tag: SNAPSHOT-PR-19-77879725
  namespaceLabels:
    label: value
    stakater.com/tenant: alpha
    owner: stakater
