apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chelsea-dev-stakater-nordmart-review
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: chelsea
    stakater.com/env: dev
    stakater.com/kind: dev         
spec:
  destination:
    namespace: chelsea-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-chelsea/01-stakater-nordmart-review-api/01-dev
    repoURL: 'https://github.com/AsfaMumtaz/nordmart-apps-gitops-config.git'
    targetRevision: HEAD
  project: chelsea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
