apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veeru-demo-stakater-nordmart-inventory
  namespace: openshift-gitops
  labels:
    stakater.com/tenant: veeru
    stakater.com/env: demo
    stakater.com/kind: demo
spec:
  destination:
    namespace: veeru-demo
    server: 'https://kubernetes.default.svc'
  source:
    path: 02-veeru/01-stakater-nordmart-inventory/04-demo
    repoURL: 'https://github.com/stakater/gitops-config-template.git'
    targetRevision: main
  project: veeru
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
