apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  annotations:
    stakater.com/repo-name: 
  name: pr-225-stakater-nordmart-review-ui-2530d0b2
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: ANOTHER-test-for-a-very-very-very-very-very-LONG-
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review-ui
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-
          version: '*'
      interval: 1m0s
      releaseName: 
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review-ui
              tag: snapshot-pr-225-2fa6879a
