apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-201-stakater-nordmart-review-ui-fe00e1fb
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: test16
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: MuneebAijaz-patch-16
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review-ui
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-MuneebAijaz-patch-16
          version: '*'
      interval: 1m0s
      releaseName: MuneebAijaz-patch-16
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review-ui
              tag: SNAPSHOT-PR-201-fe00e1fb
