apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  annotations:
    stakater.com/repo-name: stakater-nordmart-review-ui
  name: pr-227-stakater-nordmart-review-ui-8528a3e4
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: pipeline
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review-ui
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-pipeline
          version: '*'
      interval: 1m0s
      releaseName: pipeline
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review-ui
              tag: snapshot-pr-227-8528a3e4
