apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-214-stakater-nordmart-review-ui-10307081
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: test-task-creat-env-v2
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review-ui
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-test-task-creat-env-v2
          version: '*'
      interval: 1m0s
      releaseName: test-task-creat-env-v2
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review-ui
              tag: snapshot-pr-214-10307081
