apiVersion: tronador.stakater.com/v1alpha2
kind: Environment
metadata:
  name: pr-218-stakater-nordmart-review-ui-a7deb7a
spec:
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
  application:
    gitRepository:
      gitImplementation: go-git
      interval: 1m0s
      ref:
        branch: demo-pr
      timeout: 20s
      url: https://github.com/stakater-lab/stakater-nordmart-review-ui
    release:
      chart:
        spec:
          chart: deploy
          reconcileStrategy: ChartVersion
          sourceRef:
            kind: GitRepository
            name: dte-demo-pr
          version: '*'
      interval: 1m0s
      releaseName: demo-pr
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/stakater-nordmart-review-ui
              tag: snapshot-pr-218-48ab0c53
