apiVersion: tronador.stakater.com/v1alpha1
kind: EnvironmentProvisioner
metadata:
  name: pr-39-stakater-nordmart-review-ui
spec:
  application:
    release:
      chart:
        git: https://github.com/stakater-lab/stakater-nordmart-review-ui
        ref: AsfaMumtaz-patch-7
        path: deploy
        secretRef:
          null
      releaseName: AsfaMumtaz-patch-7
      valuesFrom:
        null
      values:
        application:
          deployment:
            image:
              repository: nexus-docker-stakater-nexus.apps.binero-test.8sdzwd1l.kubeapp.cloud/stakater-nordmart-review-ui
              tag: SNAPSHOT-PR-39-ff8ad640
  namespaceLabels:
    stakater.com/kind: pr
    stakater.com/tenant: gabbar
