apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: git-stakater-nordmart-review-api-git
  namespace: arsenal-build
spec:
  git_provider:
    secret:
      key: provider.token
      name: github-webhook-config
    webhook_secret:
      key: webhook.secret
      name: github-webhook-config
  url: 'hhttps://github.com/AsfaMumtaz/stakater-nordmart-review-api.git'
